# Konfiguracja ADALM-Pluto
PAYLOAD_8BITS = [ 0 , 1 , 0 , 1 , 0 , 0 , 0 , 0 ]
TEST_1BIT = [ 0 ]
PAYLOAD_1BYTE_DEC = [ 80 ]
PAYLOAD_1BYTE_HEX = [ 0x50 ]
BARKER7_BITS = [ 0 , 0 , 0 , 1 , 1 , 0 , 1 ]
BARKER13_BITS = [ 0 , 0 , 0 , 0 , 0 , 1 , 1 , 0 , 0 , 1 , 0 , 1 , 0 ]
PADDING_BITS = [ 0 , 0 , 0 ]                                            # Padding to 16 bits for BARKER13 (added at the end - LSB)
PAYLOAD_4BYTES_DEC = [ 15, 15 , 15 , 15 ]
PAYLOAD_NONE = []
cuda = "True"

[ADALM-Pluto]
F_C = 2900000000                    # center frequency
F_S = 3000000                       # sample rate
BW = 1000000                        # bandwidth
TX_GAIN = -10.0                     # transmit gain
RX_GAIN = 70                        # receive gain
GAIN_CONTROL = "slow_attack"        # gain control mode
SAMPLES_BUFFER = 614400
SAMPLES_BUFFER_SIZE = 614400

[ADALM-Pluto.URI]
IP = "ip:192.168.2.1"
USB = "usb:"
SN_RX = "10447318ac0f00091e002400454e18b77d"
SN_TX = "1044739a470b000a090018007ecf7f5ea8"

[bpsk]
SPS = 4                             # samples per symbol

[rrc_filter]
BETA = 0.35                         # roll-off factor default = 0.35
SPAN = 11                           # filter span in symbols

[log]
debugging = 1
verbose_0 = 1
verbose_1 = 1
verbose_2 = 0
tx_samples = "logs/tx_samples.csv"
rx_samples = "logs/rx_samples.csv"
tx_symbols = "logs/tx_symbols.csv"
rx_symbols = "logs/rx_symbols.csv"
rx_samples_filtered = "logs/rx_samples_filtered.csv"
rx_samples_corrected = "logs/rx_samples_corrected.csv"
rx_samples_leftovers = "logs/rx_samples_leftovers.csv"

